# Generated by Django 5.2.4 on 2025-08-04 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='lost_pets.animalcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория животного',
                'verbose_name_plural': 'Категории животных',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название района')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='lost_pets.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='LostAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон для связи')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media/lost_animals/covers', verbose_name='Обложка')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес/ориентир')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_animals', to='lost_pets.animalcategory', verbose_name='Категория животного')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_animals', to='lost_pets.city', verbose_name='Город')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_animals', to='lost_pets.district', verbose_name='Район')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_animals', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пропавшее животное',
                'verbose_name_plural': 'Пропавшие животные',
            },
        ),
        migrations.CreateModel(
            name='LostAnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/lost_animals/images', verbose_name='Фотография')),
                ('lost_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lost_pets.lostanimal', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Фотография пропавшего животного',
                'verbose_name_plural': 'Фотографии пропавших животных',
            },
        ),
    ]
