# Generated by Django 5.2.4 on 2025-08-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostanimalimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Фотография пропавшего животного', 'verbose_name_plural': 'Фотографии пропавших животных'},
        ),
        migrations.AddField(
            model_name='lostanimal',
            name='date_lost',
            field=models.DateField(blank=True, null=True, verbose_name='Дата пропажи'),
        ),
        migrations.AddField(
            model_name='lostanimal',
            name='gender',
            field=models.CharField(choices=[('male', 'Самец'), ('female', 'Самка'), ('unknown', 'Неизвестно')], default='unknown', max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='lostanimalimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
    ]
