# Generated by Django 5.2.4 on 2025-08-07 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_pets', '0002_alter_lostanimalimage_options_lostanimal_date_lost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Области'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='lost_pets.city', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='district',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='lostanimal',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_animals', to='lost_pets.city', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='lostanimal',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_animals', to='lost_pets.district', verbose_name='Город'),
        ),
    ]
